### PR TITLE
Fix tracking nonces and bundle submissions

### LINKED ISSUE #39: Nonce errors during bundle submission

### PR DESCRIPTION
**Pull request by 0xjimmy**
Resolves #39 

Ended up changing a few types, and made new the methods for calling Flashbots and checking bundle transactions.

UI/UX should be addressed to look more smooth + simple in future, the UX for this PR shouldn't have changed apart from removing errors that are either false positives or were mischaracterized as errors.

### CODE REVIEW

File: app/ts/components/Submit.tsx [hunk 1]
```diff
@@ -63,171 +72,175 @@ const SimulationResult = ({
...
+		if (!bundle.value) throw 'No imported bundle found'
+		const simulationResult = await simulateBundle(
+			bundle.value,
+			fundingAmountMin.peek(),
+			provider.value,
+			signers.peek(),
+			blockInfo.peek(),
+			appSettings.peek()
+		)
+		if ('error' in simulationResult) throw new Error((simulationResult as RelayResponseError).error.message)
```
Comment (KillariDev) [inline app/ts/components/Submit.tsx:150]: this cast is risky

File: app/ts/components/Submit.tsx [hunk 2]
```diff
@@ -63,171 +72,175 @@ const SimulationResult = ({
...
-				active: bundleStatus.value.active,
-				lastBlock: blockNumber,
-				pendingBundles: [...bundleStatus.value.pendingBundles, { hash: '', state: 'rejected', details: `RPC Error: ${blockNumber.toString()}` }],
-			}
-		})
+		if (!provider.value) throw new Error('User not connected')
+		if (!bundle.value) throw new Error('No imported bundle found')
+
+		// Check status of current bundles
+		// @DEV: Checked provider.value above, but LSP thinks it can still be undefined, so we cast it
```
Comment (KillariDev) [inline app/ts/components/Submit.tsx:163]: this is because of await, you can store it in const variable and then use that const variable

File: app/ts/components/Submit.tsx [hunk 3]
```diff
@@ -63,171 +72,175 @@ const SimulationResult = ({
...
-				lastBlock: bundleStatus.value.lastBlock,
-				pendingBundles: bundleStatus.value.pendingBundles.filter((x) => x.state === 'pending'),
+					if (!(bundleRequest.bundleHash in outstandingBundles.peek())) {
+						outstandingBundles.value = { ...outstandingBundles.peek(), [bundleRequest.bundleHash]: { targetBlock, gas, transactions: bundleRequest.bundleTransactions, included: false } }
+					}
+				} catch (error: unknown) {
+					console.error("SendBundle error", error)
+					batch(() => {
+						submissionStatus.value = { active: false, lastBlock: blockNumber }
+						outstandingBundles.value = { ...outstandingBundles.peek(), error: error as Error }
```
Comment (KillariDev) [inline app/ts/components/Submit.tsx:231]: you should check that error is actually Error and not cast it

File: app/ts/library/bundleUtils.ts [hunk 4]
```diff
@@ -54,42 +48,38 @@ export const signBundle = async (bundle: FlashbotsBundleTransaction[], provider:
...
+	bundle: Bundle | undefined,
 	signers: Signers,
 	blockInfo: BlockInfo,
 	blocksInFuture: bigint,
 	fundingAmountMin: bigint,
-	provider: providers.Web3Provider,
 ): Promise<FlashbotsBundleTransaction[]> => {
-	if (!interceptorPayload) return []
-	return await Promise.all(interceptorPayload.payload.map(async ({ from, to, nonce, gasLimit, value, input, chainId }, index) => {
+	if (!bundle) return []
```
Comment (KillariDev) [inline app/ts/library/bundleUtils.ts:64]: this could be handled outside the function and make this function only accept Bundle, then on the undefined case you would just set it []

File: app/ts/library/flashbots.ts [hunk 5]
```diff
@@ -0,0 +1,141 @@
...
+
+export async function simulateBundle(
+	bundle: Bundle,
+	fundingAmountMin: bigint,
+	provider: ProviderStore,
+	signers: Signers,
+	blockInfo: BlockInfo,
+	appSettings: AppSettings
+) {
+	if (appSettings.blocksInFuture <= 0n) throw new Error('Blocks in future is negative')
```
Comment (KillariDev) [inline app/ts/library/flashbots.ts:57]:
```suggestion
	if (appSettings.blocksInFuture <= 0n) throw new Error('Blocks in future is negative or zero')
```

File: app/ts/library/flashbots.ts [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+		gasFees: BigInt(callResult.gasFees),
+		results: callResult.results,
+		stateBlockNumber: callResult.stateBlockNumber,
+		totalGasUsed: callResult.results.reduce((a: number, b: TransactionSimulation) => a + b.gasUsed, 0),
+		firstRevert: callResult.results.find((txSim: TransactionSimulation) => 'revert' in txSim || 'error' in txSim),
+	}
+}
+
+export async function sendBundle(bundle: Bundle, targetBlock: bigint, fundingAmountMin: bigint, provider: ProviderStore, signers: Signers, blockInfo: BlockInfo, appSettings: AppSettings) {
+	if (appSettings.blocksInFuture <= 0n) throw new Error('Blocks in future is negative')
```
Comment (KillariDev) [inline app/ts/library/flashbots.ts:98]:
```suggestion
	if (appSettings.blocksInFuture <= 0n) throw new Error('Blocks in future is negative or zero')
```

File: app/ts/stores.ts [hunk 7]
```diff
@@ -28,7 +34,7 @@ function fetchPayloadFromStorage() {
 	// @TODO: Change this to track minimum amount of ETH needed to deposit
```
Comment (KillariDev) [inline app/ts/stores.ts:34]: make this an issue

File: app/ts/types/bouquetTypes.ts [hunk 8]
```diff
@@ -0,0 +1,33 @@
+import * as t from 'funtypes'
+import { EthereumAddress, EthereumInput, EthereumQuantity } from './ethereumTypes.js'
+
+export type TransactionList = t.Static<typeof TransactionList>
+export const TransactionList = t.ReadonlyArray(
+	t
```
Comment (KillariDev) [inline app/ts/types/bouquetTypes.ts:6]: this is quite weird intendation. Why not include it in the same line with the object?

Comment (0xjimmy) [reply app/ts/types/bouquetTypes.ts:6]: My TS config may be borked

File: app/ts/components/Import.tsx [hunk 9]
```diff
@@ -47,17 +54,17 @@ export async function importFromInterceptor(
 	// @TODO: Change this to track minimum amount of ETH needed to deposit
```
[the remark this answers is not in the document]
Comment (0xjimmy) [reply app/ts/components/Import.tsx:54]: https://github.com/DarkFlorist/bouquet/issues/41

File: app/ts/stores.ts (hunk 7 above)
Comment (0xjimmy) [reply app/ts/stores.ts:34]: https://github.com/DarkFlorist/bouquet/issues/41

File: app/ts/components/Import.tsx [hunk 10]
```diff
@@ -33,10 +35,15 @@ export async function importFromInterceptor(
 			}
 		})
 
-	const parsed = GetSimulationStackReply.parse(payload)
+	const tryParse = GetSimulationStackReply.safeParse(payload)
+	if (!tryParse.success) throw new Error('Import Error: Wallet does not support returning simulations')
+	const parsed = tryParse.value
 	if (parsed.length === 0) throw new Error('Import Error: You have no transactions on your simulation')
```
[the remark this answers is not in the document]
Comment (0xjimmy) [reply app/ts/components/Import.tsx:41]: The errors are shown on UI

**Review by KillariDev — APPROVED** [review]
